/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.JOptionPane;

//import java.io.BufferedReader;
//import java.io.IOException;
//import java.io.InputStream;
//import java.io.InputStreamReader;
//import java.io.OutputStream;
//import java.io.PrintWriter;
//import java.net.Socket;
//import java.net.UnknownHostException;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import java.sql.*;
//import javax.swing.JOptionPane;
//import javax.swing.*;

import net.proteanit.sql.DbUtils;
//import java.sql.PreparedStatement;


/**
 *
 * @author SNAZZY
 */
public class employee extends javax.swing.JFrame {
   
   public Connection conn;
   public Statement state;
   
   Connection emp=null;
   PreparedStatement pst=null;
  
   
  

    /**
     * Creates new form employee
     */
    public employee() {
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull","root","");
            state=conn.createStatement();
            JOptionPane.showMessageDialog(null,"WELCOME TO EMPLOYEE DETAILS!!");
            
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,e+"Error in Connecting to database!");
        }

         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);     
         
        DisplayTable();
        
    }
    private void DisplayTable()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
            String sql="select * from employee";
            
            PreparedStatement pstmt=conn.prepareStatement(sql);
            ResultSet rs=pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnAddEmp = new javax.swing.JButton();
        jbtnDeleteEmp = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jbtnReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 80, -1));

        jbtnAddEmp.setText("Add Employee");
        jbtnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddEmpActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, -1));

        jbtnDeleteEmp.setText("Delete Employee");
        jbtnDeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteEmpActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDeleteEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 120, -1));

        jbtnSave.setText("save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 90, -1));

        jbtnReport.setText("Report");
        jbtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReportActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 930, 50));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("DISMAS HOTEL");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 930, 50));

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff No", "ID No", "Staff Name", "Account No", "Residence", "Position", "Salary", "Office Tel", "Postal Code", "Address", "Mobile No", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 500));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 660, 500));

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID No");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Staff No");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Account No");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Staff Name");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Residence");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Position");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Salary");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Office Tel");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Email");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 40, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Mobile No");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 70, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Address");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 60, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Postal Code");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 80, 20));
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, 30));
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, 30));
        jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, 30));
        jPanel4.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 180, 30));
        jPanel4.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, 30));
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 170, 30));
        jPanel4.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 170, 30));
        jPanel4.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 170, 30));
        jPanel4.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 210, 30));
        jPanel4.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 180, 30));
        jPanel4.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 170, 30));
        jPanel4.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 170, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 500));

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("EMPLOYEE DETAILS");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 390, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddEmpActionPerformed
        // TODO add your handling code here:
           DefaultTableModel model = (DefaultTableModel)jTable1.getModel();        
        model.addRow(new Object[]{ jTextField14.getText(),
        jTextField15.getText(),
         jTextField16.getText(),
          jTextField13.getText(),
           jTextField17.getText(),
            jTextField18.getText(),
             jTextField19.getText(),
              jTextField20.getText(),
               jTextField24.getText(),
                jTextField23.getText(),
               jTextField22.getText(),          
                jTextField21.getText(),}); 
    }//GEN-LAST:event_jbtnAddEmpActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
           jTextField14.setText(null);
        jTextField15.setText(null);
         jTextField16.setText(null);
          jTextField13.setText(null);
           jTextField17.setText(null);
            jTextField18.setText(null);
             jTextField19.setText(null);
              jTextField20.setText(null);
                 jTextField24.setText(null);
             jTextField23.setText(null);
              jTextField22.setText(null);
                    jTextField21.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteEmpActionPerformed
        // TODO add your handling code here:
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       if (jTable1.getSelectedRow() == -1){
           if (jTable1.getRowCount() == 0){
                JOptionPane.showMessageDialog(null,"No Data to DELETE","Hotel Management System",
                       JOptionPane.OK_OPTION);
           }else{
               JOptionPane.showMessageDialog(null,"Select a Row to DELETE","Hotel Management System",
                       JOptionPane.OK_OPTION);
           }
       }else{
           model.removeRow(jTable1.getSelectedRow());
       }
    }//GEN-LAST:event_jbtnDeleteEmpActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
       String staffno=jTextField14.getText();
        String idno=jTextField15.getText();
         String staffname=jTextField16.getText();
          String accountno=jTextField13.getText();
           String residence=jTextField17.getText();
            String position=jTextField18.getText();
             String salary=jTextField19.getText();
              String officetel=jTextField20.getText();
               String postalcode=jTextField24.getText();
                String address=jTextField23.getText();
                 String mobileno=jTextField22.getText();
                  String email=jTextField21.getText();
                  Connection conn=null;
                  PreparedStatement pst=null;
                  try{
                      Class.forName("com.mysql.jdbc.Driver");
                      conn=DriverManager.getConnection("jdbc:mysql:///hotel","root","");
                      pst=conn.prepareStatement("insert into employee values(?,?,?,?,?,?,?,?,?,?,?,?)");
                      pst.setString(1,staffno);
                      pst.setString(2,idno);
                      pst.setString(3,staffname);
                      pst.setString(4,accountno);
                      pst.setString(5,residence);
                      pst.setString(6,position);
                      pst.setString(7,salary);
                      pst.setString(8,officetel);
                      pst.setString(9,postalcode);
                      pst.setString(10,address);
                      pst.setString(11,mobileno);
                      pst.setString(12,email);
                      int i=pst.executeUpdate();
                      if (i>0){
                          JOptionPane.showMessageDialog(null,"Data is saved!");
                      }
                      else {
                         JOptionPane.showMessageDialog(null,"Data is Not saved!");  
                      }
                  }
                  catch(Exception e){
                      JOptionPane.showMessageDialog(null,e); 
                  }

// TODO add your handling code here:
      //  emp=SqlConnect.ConnectDB();
      //  String sql="Insert into employee details"
       
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReportActionPerformed
        // TODO add your handling code here:
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
            String sql="select * from employee";
            
            PreparedStatement pstmt=conn.prepareStatement(sql);
            ResultSet rs=pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JButton jbtnAddEmp;
    private javax.swing.JButton jbtnDeleteEmp;
    private javax.swing.JButton jbtnReport;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSave;
    // End of variables declaration//GEN-END:variables
}
