/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import Login.Login;
import java.text.SimpleDateFormat;
import java.util.Date;
//import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.sql.*;
import java.util.Calendar;

import net.proteanit.sql.DbUtils;

/**
 *
 * @author SNAZZY
 */
public class hotel extends javax.swing.JFrame {
 public Connection conn;
   public Statement state;
   
   //Connection emp=null;
   PreparedStatement pst=null;
    /**
     * Creates new form hotel
     */
    public hotel() {
        initComponents();
         try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull","root","");
            state=conn.createStatement();
            JOptionPane.showMessageDialog(null,"HI,You are about to open DISMAS's project");
            
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,e+"Error in Connecting to database!");
        }
         
          DisplayTable(); 
       
    }
    
      private void DisplayTable()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
            String sql="select * from booking";
            
            PreparedStatement pstmt=conn.prepareStatement(sql);
            ResultSet rs=pstmt.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jbtnSave = new javax.swing.JButton();
        jbtnReport = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();
        jbtnShow = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Customer_Ref");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Surname");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Postal Code");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("ID Type");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Gender");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Check in Date");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 130, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Check Out Date");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 130, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Room Type");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 100, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Room No");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 90, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, -1));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("First Name");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("ID No");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Address");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Customer Mobile");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Nationality");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Date of Birth");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, -1));
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 140, -1));
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 220, -1));
        jPanel2.add(jDateChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 150, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Meal");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 50, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select No of Meal", "1", "2", "3" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 120, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ID Type", "National ID", "Driving Licence", "Passport", "Plot Licence", "Stident ID" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 120, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender", "Male", "Female" }));
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 120, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Room Type", "Single", "Double", "Family" }));
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 120, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Room No", "001", "002", "003", "004", "005", "006", "007", "008", "009" }));
        jPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 120, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Nationality", "Kenya", "Tanzania", "Rwanda", "Uganda", "Somalia", "Ethiopia", "Sudan", "Nigeria", "United Arab Emirates", "Jordan", "Syria", "Croatia", "Belgium", "Panama", "Malta", "Venezuela", "Taiwan", "Denmark", "Puerto Rico", "Vietnam)", "United States", "Montenegro", "Sweden", "Bolivia", "Singapore", "Bahrain", "Saudi Arabia", "Yemen", "India", "Malta", "Finland", "Latin", "Bosnia and Herzegovina", "Ukraine", "Switzerland", "Argentina", "Egypt", "Japan", "El Salvador", "Brazil", "Iceland", "Czech Republic", "Poland", "Spain", "Serbia and Montenegro", "Malaysia", "Spain", "Colombia", "Bulgaria", "Bosnia and Herzegovina", "Paraguay", "Ecuador", "United States", "Sudan", "Romania", "Philippines", "Tunisia", "Latin", "Montenegro", "Guatemala", "South Korea", "Cyprus", "Mexico", "Russia", "Honduras", "Hong Kong", "Norway", "Nynorsk", "Hungary", "Thailand", "Iraq", "Chile", "Morocco", "Ireland", "Turkey", "Estonia", "Qatar", "Portugal", "Luxembourg", "Oman", "Albania", "Dominican Republic", "Cuba", "New Zealand", "Serbia", "Switzerland", "Uruguay", "Greece", "Israel", "South Africa", "Thailand", "France", "Austria", "Norway", "Australia", "Netherlands", "Canada", "Latvia", "Luxembour", "Costa Rica", "Kuwait", "Libya", "Switzerland", "Germany", "Algeria", "Slovakia", "Lithuania", "Italy", "Ireland", "Singapore", "Canada", "Belgium", "China", "Japan", "Greece", "Serbia", "India", "Lebanon", "Nicaragua", "Macedonia", "Belarus", "Slovenia", "Peru", "Indonesia", "United Kingdom" }));
        jPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 130, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 150, -1));
        jPanel2.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, 520));

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Customer_Ref ", "First Name ", "Surname", "ID No", "Address", "Postal Code ", "Customer Mobile", " Email", "Nationality", "Date of Birth", "ID Type", "Gender", "Check in Date", "Check out Date", "Room Type", "Room No", "Meal", "Tax", "Sub Total", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel18.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 210));

        getContentPane().add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 1050, 210));

        jPanel19.setBackground(new java.awt.Color(102, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, -1));

        jButton4.setText("Room Services");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, -1));

        jButton3.setText("Meal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 1050, 40));

        jPanel27.setBackground(new java.awt.Color(102, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel27.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 80, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Total:");
        jPanel27.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Tax:");
        jPanel27.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("SubTotal:");
        jPanel27.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel27.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, 30));

        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel27.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 70, 30));

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel27.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 70, 30));

        jbtnTotal.setText("TOTAL");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });
        jPanel27.add(jbtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 70, 30));

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel27.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, -1));
        jPanel27.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 120, -1));
        jPanel27.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, -1));

        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        jPanel27.add(jbtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 70, 30));

        jbtnReport.setText("Report");
        jbtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReportActionPerformed(evt);
            }
        });
        jPanel27.add(jbtnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, 30));

        getContentPane().add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 1350, 110));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 350, 270));

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPrint.setText("PRINT RECEIPT");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 50));

        jbtnShow.setText("SHOW");
        jbtnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 300, 180, 270));

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("BOOKING");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 4, 210, 40));

        jbtnLogin.setText("Log out");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DISMAS HOTEL");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 380, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1350, 50));

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 520, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       frame = new JFrame("Exit");
       if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Hotel Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
           System.exit(0);
       }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
       if (jTable2.getSelectedRow() == -1)
       {
           if (jTable2.getRowCount() == 0){
                JOptionPane.showMessageDialog(null,"No Data to DELETE","Hotel Management System",
                       JOptionPane.OK_OPTION);
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Select a Row to DELETE","Hotel Management System",
                       JOptionPane.OK_OPTION);
           }
       }
       else
       {
           model.removeRow(jTable2.getSelectedRow());
       }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
      
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();        
        model.addRow(new Object[]{ 
        jTextField6.getText(),
        jTextField2.getText(),
         jTextField4.getText(),
          jTextField5.getText(),
           jTextField8.getText(),
            jTextField10.getText(),
             jTextField12.getText(),
              jTextField13.getText(),
               jComboBox6.getSelectedItem().toString(),
               jDateChooser1.getDate(),               
                  jComboBox2.getSelectedItem().toString(),
                  jComboBox3.getSelectedItem().toString(),
                   jDateChooser3.getDate(),
                    jDateChooser4.getDate(),
                  jComboBox4.getSelectedItem().toString(),
                  jComboBox5.getSelectedItem().toString(),
                   jComboBox1.getSelectedItem().toString(),
         jTextField11.getText(),
             jTextField14.getText(),
              jTextField15.getText(),});                 
                     
                   
                       
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
             
       jTextField6.setText(null);
        jTextField2.setText(null);
         jTextField4.setText(null);
          jTextField5.setText(null);
           jTextField8.setText(null);
            jTextField10.setText(null);
             jTextField12.setText(null);
              jTextField13.setText(null);
               jTextField11.setText(null);
                jTextField14.setText(null);
                 jTextField15.setText(null);
                  jComboBox2.setSelectedIndex(0);
                  jComboBox3.setSelectedIndex(0);
                  jComboBox4.setSelectedIndex(0);
                  jComboBox5.setSelectedIndex(0);
                   jComboBox1.setSelectedIndex(0);
                    jDateChooser1.setDate(null);
                     jDateChooser3.setDate(null);
                      jDateChooser4.setDate(null);
                        jComboBox6.setSelectedIndex(0); 
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
       int SingleRoom=6;
       int DoubleRoom=15;
       int FamilyRoom=40;
       
       int oneMeal=7;
       int twoMeals=15;
       int threeMeals=30;
       SimpleDateFormat format = new SimpleDateFormat ("yyyy-MM-dd");
       Date Check_In_Date=null;
        Date Check_Out_Date=null;
       
       try {
        Check_In_Date= format.parse(format.format(jDateChooser3.getDate()));
        Check_Out_Date= format.parse(format.format(jDateChooser4.getDate()));
           
       } 
       catch(Exception e)
       {
          e.printStackTrace();
       }
       long Checkdiff = Check_Out_Date.getTime() - Check_In_Date.getTime();
       int Daysdiff = (int)(Checkdiff/1000/60/60/24);
       if (jComboBox4.getSelectedItem().equals("Single") && jComboBox1.getSelectedItem().equals("1"))
       {
           jTextField11.setText(Integer.toString(Daysdiff * SingleRoom)+ oneMeal);
            jTextField14.setText(Integer.toString(Daysdiff * SingleRoom)+ oneMeal);
             jTextField15.setText(Integer.toString(Daysdiff * SingleRoom)+ oneMeal);
             
             double q = Double.parseDouble(jTextField11.getText());
             q = (q*0.25)/100;
             String tax = String.format(("$ %.2f"),q);
             jTextField11.setText(tax);
             
             double st = Double.parseDouble(jTextField14.getText());
             st = (st);
             String subtotal = String.format(("$ %.2f"),st);
             jTextField14.setText(subtotal);
             
             double tt = Double.parseDouble(jTextField15.getText());
             tt = (tt);
             String total = String.format(("$ %.2f"),tt+q);
             jTextField15.setText(total);
       }
       
        //====================================================================
       else if (jComboBox4.getSelectedItem().equals("Double") && jComboBox1.getSelectedItem().equals("1"))
       {
           jTextField11.setText(Integer.toString(Daysdiff * DoubleRoom)+ oneMeal);
            jTextField14.setText(Integer.toString(Daysdiff * DoubleRoom)+ oneMeal);
             jTextField15.setText(Integer.toString(Daysdiff * DoubleRoom)+ oneMeal);
             
             double q = Double.parseDouble(jTextField11.getText());
             q = (q*0.25)/100;
             String tax = String.format(("$ %.2f"),q);
             jTextField11.setText(tax);
             
             double st = Double.parseDouble(jTextField14.getText());
             st = (st);
             String subtotal = String.format(("$ %.2f"),st);
             jTextField14.setText(subtotal);
             
             double tt = Double.parseDouble(jTextField15.getText());
             tt = (tt);
             String total = String.format(("$ %.2f"),tt+q);
             jTextField15.setText(total);
       }
       //====================================================================
        else if (jComboBox4.getSelectedItem().equals("Family") && jComboBox1.getSelectedItem().equals("1"))
       {
           jTextField11.setText(Integer.toString(Daysdiff * FamilyRoom)+ oneMeal);
            jTextField14.setText(Integer.toString(Daysdiff * FamilyRoom)+ oneMeal);
             jTextField15.setText(Integer.toString(Daysdiff * FamilyRoom)+ oneMeal);
             
             double q = Double.parseDouble(jTextField11.getText());
             q = (q*0.25)/100;
             String tax = String.format(("$ %.2f"),q);
             jTextField11.setText(tax);
             
             double st = Double.parseDouble(jTextField14.getText());
             st = (st);
             String subtotal = String.format(("$ %.2f"),st);
             jTextField14.setText(subtotal);
             
             double tt = Double.parseDouble(jTextField15.getText());
             tt = (tt);
             String total = String.format(("$ %.2f"),tt+q);
             jTextField15.setText(total);
       }
       //====================================================================
          if (jComboBox4.getSelectedItem().equals("Single") && jComboBox1.getSelectedItem().equals("2"))
       {
           jTextField11.setText(Integer.toString(Daysdiff * SingleRoom)+ twoMeals);
            jTextField14.setText(Integer.toString(Daysdiff * SingleRoom)+ twoMeals);
             jTextField15.setText(Integer.toString(Daysdiff * SingleRoom)+ twoMeals);
             
             double q = Double.parseDouble(jTextField11.getText());
             q = (q*0.25)/100;
             String tax = String.format(("$ %.2f"),q);
             jTextField11.setText(tax);
             
             double st = Double.parseDouble(jTextField14.getText());
             st = (st);
             String subtotal = String.format(("$ %.2f"),st);
             jTextField14.setText(subtotal);
             
             double tt = Double.parseDouble(jTextField15.getText());
             tt = (tt);
             String total = String.format(("$ %.2f"),tt+q);
             jTextField15.setText(total);
       }
       //====================================================================
          else if (jComboBox4.getSelectedItem().equals("Double") && jComboBox1.getSelectedItem().equals("2"))
       {
           jTextField11.setText(Integer.toString(Daysdiff * DoubleRoom)+ twoMeals);
            jTextField14.setText(Integer.toString(Daysdiff * DoubleRoom)+ twoMeals);
             jTextField15.setText(Integer.toString(Daysdiff * DoubleRoom)+ twoMeals);
             
             double q = Double.parseDouble(jTextField11.getText());
             q = (q*0.25)/100;
             String tax = String.format(("$ %.2f"),q);
             jTextField11.setText(tax);
             
             double st = Double.parseDouble(jTextField14.getText());
             st = (st);
             String subtotal = String.format(("$ %.2f"),st);
             jTextField14.setText(subtotal);
             
             double tt = Double.parseDouble(jTextField15.getText());
             tt = (tt);
             String total = String.format(("$ %.2f"),tt+q);
             jTextField15.setText(total);
       }
       //====================================================================
           else if (jComboBox4.getSelectedItem().equals("Family") && jComboBox1.getSelectedItem().equals("2"))
       {
           jTextField11.setText(Integer.toString(Daysdiff * FamilyRoom)+ twoMeals);
            jTextField14.setText(Integer.toString(Daysdiff * FamilyRoom)+ twoMeals);
             jTextField15.setText(Integer.toString(Daysdiff * FamilyRoom)+ twoMeals);
             
             double q = Double.parseDouble(jTextField11.getText());
             q = (q*0.25)/100;
             String tax = String.format(("$ %.2f"),q);
             jTextField11.setText(tax);
             
             double st = Double.parseDouble(jTextField14.getText());
             st = (st);
             String subtotal = String.format(("$ %.2f"),st);
             jTextField14.setText(subtotal);
             
             double tt = Double.parseDouble(jTextField15.getText());
             tt = (tt);
             String total = String.format(("$ %.2f"),tt+q);
             jTextField15.setText(total);
       }
       //====================================================================
             if (jComboBox4.getSelectedItem().equals("Single") && jComboBox1.getSelectedItem().equals("3"))
       {
           jTextField11.setText(Integer.toString(Daysdiff * SingleRoom)+ threeMeals);
            jTextField14.setText(Integer.toString(Daysdiff * SingleRoom)+ threeMeals);
             jTextField15.setText(Integer.toString(Daysdiff * SingleRoom)+ threeMeals);
             
             double q = Double.parseDouble(jTextField11.getText());
             q = (q*0.25)/100;
             String tax = String.format(("$ %.2f"),q);
             jTextField11.setText(tax);
             
             double st = Double.parseDouble(jTextField14.getText());
             st = (st);
             String subtotal = String.format(("$ %.2f"),st);
             jTextField14.setText(subtotal);
             
             double tt = Double.parseDouble(jTextField15.getText());
             tt = (tt);
             String total = String.format(("$ %.2f"),tt+q);
             jTextField15.setText(total);
       }
       //====================================================================
             else if (jComboBox4.getSelectedItem().equals("Double") && jComboBox1.getSelectedItem().equals("3"))
       {
           jTextField11.setText(Integer.toString(Daysdiff * DoubleRoom)+ threeMeals);
            jTextField14.setText(Integer.toString(Daysdiff * DoubleRoom)+ threeMeals);
             jTextField15.setText(Integer.toString(Daysdiff * DoubleRoom)+ threeMeals);
             
             double q = Double.parseDouble(jTextField11.getText());
             q = (q*0.25)/100;
             String tax = String.format(("$ %.2f"),q);
             jTextField11.setText(tax);
             
             double st = Double.parseDouble(jTextField14.getText());
             st = (st);
             String subtotal = String.format(("$ %.2f"),st);
             jTextField14.setText(subtotal);
             
             double tt = Double.parseDouble(jTextField15.getText());
             tt = (tt);
             String total = String.format(("$ %.2f"),tt+q);
             jTextField15.setText(total);
       }
       //====================================================================
             else  if (jComboBox4.getSelectedItem().equals("Family") && jComboBox1.getSelectedItem().equals("3"))
       {
           jTextField11.setText(Integer.toString(Daysdiff * FamilyRoom)+ threeMeals);
            jTextField14.setText(Integer.toString(Daysdiff * FamilyRoom)+ threeMeals);
             jTextField15.setText(Integer.toString(Daysdiff * FamilyRoom)+ threeMeals);
             
             double q = Double.parseDouble(jTextField11.getText());
             q = (q*0.25)/100;
             String tax = String.format(("$ %.2f"),q);
             jTextField11.setText(tax);
             
             double st = Double.parseDouble(jTextField14.getText());
             st = (st);
             String subtotal = String.format(("$ %.2f"),st);
             jTextField14.setText(subtotal);
             
             double tt = Double.parseDouble(jTextField15.getText());
             tt = (tt);
             String total = String.format(("$ %.2f"),tt+q);
             jTextField15.setText(total);
       }      
                      
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        Login iLogin =new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        try{
            area.print();
        }catch (PrinterException ex){
            Logger.getLogger(hotel.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowActionPerformed
      
        area.setText("********************************************************\n");
       area.setText(area.getText()+"*                                       DISMAS HOTEL       *\n\n"+"BOOKING RECEIPT       \n");
       area.setText(area.getText()+"********************************************************\n");    
       
       Date obj=new Date();
       String date =obj.toString();
       
         area.setText(area.getText()+"\n"+date+"\n\n");        
           area.setText(area.getText()+"Customer Ref:"+jTextField6.getText()+"\n");
            area.setText(area.getText()+"First Name:"+jTextField2.getText()+"\n");
            area.setText(area.getText()+"Surname:"+jTextField4.getText()+"\n");
            area.setText(area.getText()+"ID No:"+jTextField5.getText()+"\n");
            area.setText(area.getText()+"Customer Mobile:"+jTextField12.getText()+"\n");
            area.setText(area.getText()+"Email:"                              +jTextField13.getText()+"\n");
            area.setText(area.getText()+"Check in Date:"+jDateChooser3.getDate().toLocaleString()+"\n");
            area.setText(area.getText()+"Check out Date:"+jDateChooser4.getDate().toLocaleString()+"\n");
            area.setText(area.getText()+"Room Type:"+jComboBox4.getSelectedItem()+"\n");
            area.setText(area.getText()+"Room No:"+jComboBox5.getSelectedItem()+"\n");
            area.setText(area.getText()+"Meal:"+jComboBox1.getSelectedItem()+"\n");
            area.setText(area.getText()+"Tax:"+jTextField11.getText()+"\n");
            area.setText(area.getText()+"Sub Total:"+jTextField14.getText()+"\n");
            area.setText(area.getText()+"Total:"+jTextField15.getText()+"\n");
                                     area.setText(area.getText()+"\n        WELCOME!! AND THANK YOU FOR"+"\n CHOOSING DISMAS HOTEL,"+"\n FEEL AT HOME"+"\n        CONTACT:0722476796");
      
    }//GEN-LAST:event_jbtnShowActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:     
        
        employee emp = new employee();
        emp.show();
        //dispose();
        //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          Meal mel = new Meal();
        mel.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          RoomServices ser = new RoomServices();
        ser.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:
         String customerref=jTextField6.getText();
        String firstname=jTextField2.getText();
         String surname=jTextField4.getText();
          String idno=jTextField5.getText();
           String address=jTextField8.getText();
            String postalcode=jTextField10.getText();
             String customermobile=jTextField12.getText();
              String email=jTextField13.getText();
               String nationality=jComboBox6.getSelectedItem().toString();
            String dob=jDateChooser1.getDate().toLocaleString();
               String idtype=jComboBox2.getSelectedItem().toString();                     
                String gender=jComboBox3.getSelectedItem().toString();
              String checkindate=jDateChooser3.getDate().toLocaleString();
              String checkoutdate=jDateChooser4.getDate().toLocaleString();
               String roomtype=jComboBox4.getSelectedItem().toString();                     
                String roomno=jComboBox5.getSelectedItem().toString();
               String meal=jComboBox1.getSelectedItem().toString();                 
                String tax=jTextField11.getText();
                  String subtotal=jTextField14.getText();
                   String total=jTextField15.getText();
                  Connection conn=null;
                  PreparedStatement pst=null;
                  try{
                      Class.forName("com.mysql.jdbc.Driver");
                      conn=DriverManager.getConnection("jdbc:mysql:///hotel","root","");
                      pst=conn.prepareStatement("insert into booking values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                      pst.setString(1,customerref);
                      pst.setString(2,firstname);
                      pst.setString(3,surname);
                      pst.setString(4,idno);
                      pst.setString(5,address);
                      pst.setString(6,postalcode);
                      pst.setString(7,customermobile);
                      pst.setString(8,email);
                     pst.setString(9,nationality);                   
                      pst.setString(10,dob);
                      pst.setString(11,idtype);
                     pst.setString(12,gender);
                     pst.setString(13,checkindate);
                     pst.setString(14,checkoutdate);
                      pst.setString(15,roomtype);
                      pst.setString(16,roomno);
                      pst.setString(17,meal);
                       pst.setString(18,tax);
                        pst.setString(19,subtotal);
                         pst.setString(20,total);
                      int i=pst.executeUpdate();
                      if (i>0){
                          JOptionPane.showMessageDialog(null,"Data is saved!");
                      }
                      else {
                         JOptionPane.showMessageDialog(null,"Data is Not saved!");  
                      }
                  }
                  catch(Exception e){
                      JOptionPane.showMessageDialog(null,e); 
                  }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReportActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
            String sql="select * from booking";
            
            PreparedStatement pstmt=conn.prepareStatement(sql);
            ResultSet rs=pstmt.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReport;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnShow;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JButton jbtnUpdate;
    // End of variables declaration//GEN-END:variables
}
