/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.print.PrinterException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import net.proteanit.sql.DbUtils;
/**
 *
 * @author SNAZZY
 */
public class Meal extends javax.swing.JFrame {
 public Connection conn;
   public Statement state;
   
   Connection emp=null;
   PreparedStatement pst=null;
    /**
     * Creates new form Meal
     */
    public Meal() {
        initComponents();
         try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull","root","");
            state=conn.createStatement();
            JOptionPane.showMessageDialog(null,"WELCOME TO MEAL!!");
            
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,e+"Error in Connecting to database!");
        }
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         
          DisplayTable(); 
    }
    
      private void DisplayTable()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
            String sql="select * from meal";
            
            PreparedStatement pstmt=conn.prepareStatement(sql);
            ResultSet rs=pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jbtnTotal = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jbtnReport = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();
        jbtnShow = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("MEAL");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 120, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 50));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("DISMAS HOTEL");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 230, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 930, 50));

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("First Name");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Customer Ref");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID No");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Surname");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Address");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Postal Code");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Mobile No");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Email");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("No of Orders");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 80, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Date");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 50, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Room No");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 60, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Nationality");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 20));
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, 30));
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 30));
        jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 160, 30));
        jPanel4.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 170, 30));
        jPanel4.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, 30));
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 160, 30));
        jPanel4.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, 30));
        jPanel4.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 170, 30));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Nationality", "Kenya", "Tanzania", "Rwanda", "Uganda", "Somalia", "Ethiopia", "Sudan", "Nigeria", "United Arab Emirates", "Jordan", "Syria", "Croatia", "Belgium", "Panama", "Malta", "Venezuela", "Taiwan", "Denmark", "Puerto Rico", "Vietnam)", "United States", "Montenegro", "Sweden", "Bolivia", "Singapore", "Bahrain", "Saudi Arabia", "Yemen", "India", "Malta", "Finland", "Latin", "Bosnia and Herzegovina", "Ukraine", "Switzerland", "Argentina", "Egypt", "Japan", "El Salvador", "Brazil", "Iceland", "Czech Republic", "Poland", "Spain", "Serbia and Montenegro", "Malaysia", "Spain", "Colombia", "Bulgaria", "Bosnia and Herzegovina", "Paraguay", "Ecuador", "United States", "Sudan", "Romania", "Philippines", "Tunisia", "Latin", "Montenegro", "Guatemala", "South Korea", "Cyprus", "Mexico", "Russia", "Honduras", "Hong Kong", "Norway", "Nynorsk", "Hungary", "Thailand", "Iraq", "Chile", "Morocco", "Ireland", "Turkey", "Estonia", "Qatar", "Portugal", "Luxembourg", "Oman", "Albania", "Dominican Republic", "Cuba", "New Zealand", "Serbia", "Switzerland", "Uruguay", "Greece", "Israel", "South Africa", "Thailand", "France", "Austria", "Norway", "Australia", "Netherlands", "Canada", "Latvia", "Luxembour", "Costa Rica", "Kuwait", "Libya", "Switzerland", "Germany", "Algeria", "Slovakia", "Lithuania", "Italy", "Ireland", "Singapore", "Canada", "Belgium", "China", "Japan", "Greece", "Serbia", "India", "Lebanon", "Nicaragua", "Macedonia", "Belarus", "Slovenia", "Peru", "Indonesia", "United Kingdom" }));
        jPanel4.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 150, 30));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Room No", "001", "002", "003", "004", "005", "006", "007", "008", "009" }));
        jPanel4.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 150, 30));
        jPanel4.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 170, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a  Meal", "Breakfast", "Lunch", "Dinner" }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 170, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Meal");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 40, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select No of Orders", "1", "2", "3", "4" }));
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 160, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 540));

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Ref", "First Name", "Surname", "ID No", "Address", "Postal Code", "Mobile No", "Email", "Nationality", "Room No", "Date", "Meal", "No of Orders", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 190));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 660, 190));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 70, -1));

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 70, -1));

        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("TOTAL:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));
        jPanel1.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, 30));

        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 70, -1));

        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jbtnReport.setText("Report");
        jbtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReportActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 930, 50));

        jPanel6.setBackground(new java.awt.Color(102, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPrint.setText("PRINT RECEIPT");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 140, 50));

        jbtnShow.setText("SHOW");
        jbtnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 140, 50));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 350));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 660, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();        
        model.addRow(new Object[]{ jTextField14.getText(),
        jTextField15.getText(),
         jTextField16.getText(),
          jTextField13.getText(),
           jTextField17.getText(),
            jTextField18.getText(),
             jTextField19.getText(),
              jTextField20.getText(),
               jComboBox6.getSelectedItem().toString(),
               jComboBox5.getSelectedItem().toString(),
               jDateChooser3.getDate(),          
                jComboBox1.getSelectedItem().toString(),
                 jComboBox2.getSelectedItem().toString(),
                  jTextField21.getText(),});   
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
          jTextField14.setText(null);
        jTextField15.setText(null);
         jTextField16.setText(null);
          jTextField13.setText(null);
           jTextField17.setText(null);
            jTextField18.setText(null);
             jTextField19.setText(null);
              jTextField20.setText(null);
                jComboBox6.setSelectedIndex(0);
                jComboBox5.setSelectedIndex(0);
                 jDateChooser3.setDate(null);
                  jComboBox1.setSelectedIndex(0);
                   jComboBox2.setSelectedIndex(0);
                    jTextField21.setText(null);
                
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       if (jTable1.getSelectedRow() == -1){
           if (jTable1.getRowCount() == 0){
                JOptionPane.showMessageDialog(null,"No Data to DELETE","Hotel Management System",
                       JOptionPane.OK_OPTION);
           }else{
               JOptionPane.showMessageDialog(null,"Select a Row to DELETE","Hotel Management System",
                       JOptionPane.OK_OPTION);
           }
       }else{
           model.removeRow(jTable1.getSelectedRow());
       }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:   
         
       String customerref=jTextField14.getText();          
        String firstname=jTextField15.getText();
        String surname=jTextField16.getText();
          String idno=jTextField13.getText();
           String address=jTextField17.getText();
            String postalcode=jTextField18.getText();
             String mobileno=jTextField19.getText();
              String email=jTextField20.getText();
               String nationality=jComboBox6.getSelectedItem().toString();
               String roomno=jComboBox5.getSelectedItem().toString();
               String date=jDateChooser3.getDate().toLocaleString();         
                String meal=jComboBox1.getSelectedItem().toString();
                 String noofmeals=jComboBox2.getSelectedItem().toString();
              String total=jTextField21.getText();
                  Connection conn=null;
                  PreparedStatement pst=null;
                 
                  try{
                      Class.forName("com.mysql.jdbc.Driver");
                      conn=DriverManager.getConnection("jdbc:mysql:///hotel","root","");
                      pst=conn.prepareStatement("insert into meal values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                      pst.setString(1,customerref);
                      pst.setString(2,firstname);
                      pst.setString(3,surname);
                      pst.setString(4,idno);
                      pst.setString(5,address);
                      pst.setString(6,postalcode);
                      pst.setString(7,mobileno);
                      pst.setString(8,email);
                      pst.setString(9,nationality);
                      pst.setString(10,roomno);
                      pst.setString(11,date);
                     pst.setString(12,meal);
                       pst.setString(13,noofmeals);
                       pst.setString(14,total);
                      int i=pst.executeUpdate();
                      if (i>0){
                          JOptionPane.showMessageDialog(null,"Data is saved!");
                      }
                      else {
                         JOptionPane.showMessageDialog(null,"Data is Not saved!");  
                      }
                  }
                  catch(Exception e){
                      JOptionPane.showMessageDialog(null,e); 
                  }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReportActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
            String sql="select * from meal";
            
            PreparedStatement pstmt=conn.prepareStatement(sql);
            ResultSet rs=pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnReportActionPerformed

    private void jbtnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowActionPerformed
        // TODO add your handling code here:
          area.setText("********************************************************\n");
       area.setText(area.getText()+"*                                       DISMAS HOTEL       *\n\n"+"MEAL RECEIPT       \n");
       area.setText(area.getText()+"********************************************************\n");    
       
       java.util.Date obj=new java.util.Date();
       String date =obj.toString();
       
         area.setText(area.getText()+"\n"+date+"\n\n");        
           area.setText(area.getText()+"Customer Ref:"+jTextField14.getText()+"\n");
            area.setText(area.getText()+"First Name:"+jTextField15.getText()+"\n");
            area.setText(area.getText()+"Surname:"+jTextField16.getText()+"\n");
            area.setText(area.getText()+"ID No:"+jTextField13.getText()+"\n");
            area.setText(area.getText()+"Address:"+jTextField17.getText()+"\n");
            area.setText(area.getText()+"Postal Code:"+jTextField18.getText()+"\n");
              area.setText(area.getText()+"Mobile No:"+jTextField19.getText()+"\n");
            area.setText(area.getText()+"Email:"+jTextField20.getText()+"\n");
             area.setText(area.getText()+"Nationality:"+jComboBox6.getSelectedItem()+"\n");
            area.setText(area.getText()+"Room No:"+jComboBox5.getSelectedItem()+"\n");            
            area.setText(area.getText()+"Date:"+jDateChooser3.getDate().toLocaleString()+"\n");
             area.setText(area.getText()+"Meal:"+jComboBox1.getSelectedItem()+"\n");
              area.setText(area.getText()+"No of Meals:"+jComboBox2.getSelectedItem()+"\n");  
              area.setText(area.getText()+"Total:"+jTextField21.getText()+"\n");
                                     area.setText(area.getText()+"\n        WELCOME!! AGAIN TO A HOME OF"+"\n DELICIOUS MEALS"+"\n        CONTACT:0722476796");
    }//GEN-LAST:event_jbtnShowActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        int one=1;
         int two=2;
          int three=3;     
        int four=4; 
        
          int Breakfast=7;
        int Lunch=10;
        int Dinner=15;
        
         if(jComboBox1.getSelectedItem().equals("Breakfast") && jComboBox2.getSelectedItem().equals("1"))
        {
            jTextField21.setText(Integer.toString(Breakfast*one));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
          else if(jComboBox1.getSelectedItem().equals("Lunch") && jComboBox2.getSelectedItem().equals("1"))
        {
            jTextField21.setText(Integer.toString(Lunch*one));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
           else if(jComboBox1.getSelectedItem().equals("Dinner") && jComboBox2.getSelectedItem().equals("1"))
        {
            jTextField21.setText(Integer.toString(Dinner*one));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
           //===================================================================================
             if(jComboBox1.getSelectedItem().equals("Breakfast") && jComboBox2.getSelectedItem().equals("2"))
        {
            jTextField21.setText(Integer.toString(Breakfast*two));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
          else if(jComboBox1.getSelectedItem().equals("Lunch") && jComboBox2.getSelectedItem().equals("2"))
        {
            jTextField21.setText(Integer.toString(Lunch*two));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
           else if(jComboBox1.getSelectedItem().equals("Dinner") && jComboBox2.getSelectedItem().equals("2"))
        {
            jTextField21.setText(Integer.toString(Dinner*two));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
         //===================================================================================
             if(jComboBox1.getSelectedItem().equals("Breakfast") && jComboBox2.getSelectedItem().equals("3"))
        {
            jTextField21.setText(Integer.toString(Breakfast*three));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
          else if(jComboBox1.getSelectedItem().equals("Lunch") && jComboBox2.getSelectedItem().equals("3"))
        {
            jTextField21.setText(Integer.toString(Lunch*three));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
           else if(jComboBox1.getSelectedItem().equals("Dinner") && jComboBox2.getSelectedItem().equals("3"))
        {
            jTextField21.setText(Integer.toString(Dinner*three));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
       //===================================================================================
               if(jComboBox1.getSelectedItem().equals("Breakfast") && jComboBox2.getSelectedItem().equals("4"))
        {
            jTextField21.setText(Integer.toString(Breakfast*four));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
          else if(jComboBox1.getSelectedItem().equals("Lunch") && jComboBox2.getSelectedItem().equals("4"))
        {
            jTextField21.setText(Integer.toString(Lunch*four));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
           else if(jComboBox1.getSelectedItem().equals("Dinner") && jComboBox2.getSelectedItem().equals("4"))
        {
            jTextField21.setText(Integer.toString(Dinner*four));
            
            double tt=Double.parseDouble(jTextField21.getText());
            tt=(tt);
            String total=String.format(("$ %.2f"), tt);
            jTextField21.setText(total);
        }
       
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
          try{
            area.print();
        }catch (PrinterException ex){
            Logger.getLogger(hotel.class.getName()).log(Level.SEVERE,null,ex);
        }
           
    }//GEN-LAST:event_jbtnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReport;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnShow;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JButton jbtnUpdate;
    // End of variables declaration//GEN-END:variables
   
}
